Question 1)	Define the following metrics and perform the following operations
i)	Write a Python program using Python Lists
ii)	Write a Python program and NumPy

Matrix A =  [[ 3.7827  3.3454  3.2341]  , [ 2.2122  3.5678  3.9087] , 
[1.1234  2.8934,  5.9087]].

Matrix B =  [[ 3.1234  3.0987  3.1234]  , [ 2.1111  3.2222  3.3333] , 
[1.0987  1.3456,  5.1234]].

Matrix C =  [[ 3.1243  3.0989  3.1256 ]  , [ 2.6721  3.6785  3.9017] , 
[1.1254  2.8956,  5.9187]].


In [17]:
# Matrices using Python lists
A = [[3.7827, 3.3454, 3.2341], [2.2122, 3.5678, 3.9087], [1.1234, 2.8934, 5.9087]]
B = [[3.1234, 3.0987, 3.1234], [2.1111, 3.2222, 3.3333], [1.0987, 1.3456, 5.1234]]
C = [[3.1243, 3.0989, 3.1256], [2.6721, 3.6785, 3.9017], [1.1254, 2.8956, 5.9187]]

# Matrix addition A + B
def add_matrices(matrix1, matrix2):
    result = [[matrix1[i][j] + matrix2[i][j] for j in range(len(matrix1[0]))] for i in range(len(matrix1))]
    return result

# Matrix subtraction A - C
def subtract_matrices(matrix1, matrix2):
    result = [[matrix1[i][j] - matrix2[i][j] for j in range(len(matrix1[0]))] for i in range(len(matrix1))]
    return result

# Matrix multiplication A * B
def multiply_matrices(matrix1, matrix2):
    result = [[0 for _ in range(len(matrix2[0]))] for _ in range(len(matrix1))]
    for i in range(len(matrix1)):
        for j in range(len(matrix2[0])):
            for k in range(len(matrix2)):
                result[i][j] += matrix1[i][k] * matrix2[k][j]
    return result

# Performing operations
add_result = add_matrices(A, B)
subtract_result = subtract_matrices(A, C)
multiply_result = multiply_matrices(A, B)

print("Matrix A + B:\n", add_result)
print("\nMatrix A - C:\n", subtract_result)
print("\nMatrix A * B:\n", multiply_result)

#profile the operation by list
import cProfile
def profile_list_operations():
    add_matrices(A, B)
    subtract_matrices(A, C)
    multiply_matrices(A, B)

cProfile.run('profile_list_operations()')

Matrix A + B:
 [[6.9061, 6.444100000000001, 6.3575], [4.3233, 6.79, 7.242], [2.2221, 4.239, 11.0321]]

Matrix A - C:
 [[0.6584000000000003, 0.24650000000000016, 0.10850000000000026], [-0.45989999999999975, -0.11070000000000002, 0.007000000000000117], [-0.0020000000000000018, -0.0021999999999997577, -0.010000000000000675]]

Matrix A * B:
 [[22.43066479, 26.85280533, 39.53569494], [18.736056750000003, 23.61065602, 38.8279668], [16.108972989999998, 20.754939779999997, 43.42603136]]
         32 function calls in 0.001 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.000    0.000 2223720578.py:12(subtract_matrices)
        1    0.000    0.000    0.000    0.000 2223720578.py:17(multiply_matrices)
        1    0.000    0.000    0.000    0.000 2223720578.py:36(profile_list_operations)
        1    0.000    0.000    0.000    0.000 2223720578.py:7(add_matrices)
        1    0.000    0.000    0.000    0

Matrices Operations Using NumPy

In [19]:
# Matrices using NumPy
import numpy as np

# Define matrices using NumPy arrays
A = np.array([[3.7827, 3.3454, 3.2341], [2.2122, 3.5678, 3.9087], [1.1234, 2.8934, 5.9087]])
B = np.array([[3.1234, 3.0987, 3.1234], [2.1111, 3.2222, 3.3333], [1.0987, 1.3456, 5.1234]])
C = np.array([[3.1243, 3.0989, 3.1256], [2.6721, 3.6785, 3.9017], [1.1254, 2.8956, 5.9187]])

# Matrix addition A + B
add_result = np.add(A, B)

# Matrix subtraction A - C
subtract_result = np.subtract(A, C)

# Matrix multiplication A * B
multiply_result = np.dot(A, B)

print("Matrix A + B:\n", add_result)
print("\nMatrix A - C:\n", subtract_result)
print("\nMatrix A * B:\n", multiply_result)

def add_matrices(A, B):
    return np.add(A, B)

def subtract_matrices(A, B):
    return np.subtract(A, C)

def multiply_matrices(A, B):
    return np.dot(A, B)
    
#profile the operation by list
import cProfile
def profile_list_operations():
    add_matrices(A, B)
    subtract_matrices(A, C)
    multiply_matrices(A, B)

cProfile.run('profile_list_operations()')


Matrix A + B:
 [[ 6.9061  6.4441  6.3575]
 [ 4.3233  6.79    7.242 ]
 [ 2.2221  4.239  11.0321]]

Matrix A - C:
 [[ 0.6584  0.2465  0.1085]
 [-0.4599 -0.1107  0.007 ]
 [-0.002  -0.0022 -0.01  ]]

Matrix A * B:
 [[22.43066479 26.85280533 39.53569494]
 [18.73605675 23.61065602 38.8279668 ]
 [16.10897299 20.75493978 43.42603136]]
         8 function calls in 0.000 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.000    0.000 3908378266.py:22(add_matrices)
        1    0.000    0.000    0.000    0.000 3908378266.py:25(subtract_matrices)
        1    0.000    0.000    0.000    0.000 3908378266.py:28(multiply_matrices)
        1    0.000    0.000    0.000    0.000 3908378266.py:33(profile_list_operations)
        1    0.000    0.000    0.000    0.000 <string>:1(<module>)
        1    0.000    0.000    0.000    0.000 multiarray.py:741(dot)
        1    0.000    0.000    0.000    0.000 {built-in meth

Question2)	Write a Python Program and perform the following operations ?
I.	Create a List {1225, 4986, 6789, 7890, 2345, 6783, 0987, 1234, 8765, 3456}
II.	Iterate using a for loop
III.	Iterate using for loop and range
IV.	List Comprehension
V.	Enumerate
VI.	Iter function and next function
VII.	Map function
VIII.	Using zip
IX.	Using NumPy Module


In [22]:
# Step I: Create a List
numbers = [1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]

# Step II: Iterate using a for loop
print("II. Iterating using a for loop:")
for num in numbers:
    print(num, end=" ")
print("\n")

# Step III: Iterate using for loop and range
print("III. Iterating using for loop and range:")
for i in range(len(numbers)):
    print(numbers[i], end=" ")
print("\n")

# Step IV: List Comprehension
print("IV. List Comprehension (Squared Values):")
squared_numbers = [num**2 for num in numbers]
print(squared_numbers)
print()

# Step V: Enumerate
print("V. Enumerate:")
for index, num in enumerate(numbers):
    print(f"Index {index} => {num}")
print()

# Step VI: Iter function and next function
print("VI. Using iter and next:")
numbers_iter = iter(numbers)
while True:
    try:
        print(next(numbers_iter), end=" ")
    except StopIteration:
        break
print("\n")

# Step VII: Map function (Double the values)
print("VII. Using map function (Double the values):")
doubled_numbers = list(map(lambda x: x * 2, numbers))
print(doubled_numbers)
print()

# Step VIII: Using zip (Pair with reversed list)
print("VIII. Using zip:")
paired_with_reversed = list(zip(numbers, reversed(numbers)))
print(paired_with_reversed)
print()

# Step IX: Using NumPy Module (Array operations)
import numpy as np

print("IX. Using NumPy Module:")
np_numbers = np.array(numbers)
# Perform operations like mean, sum, square of each element
print("NumPy Array:", np_numbers)
print("Sum of elements:", np.sum(np_numbers))
print("Mean of elements:", np.mean(np_numbers))
print("Squared elements:", np_numbers**2)


II. Iterating using a for loop:
1225 4986 6789 7890 2345 6783 987 1234 8765 3456 

III. Iterating using for loop and range:
1225 4986 6789 7890 2345 6783 987 1234 8765 3456 

IV. List Comprehension (Squared Values):
[1500625, 24860196, 46090521, 62252100, 5499025, 46009089, 974169, 1522756, 76825225, 11943936]

V. Enumerate:
Index 0 => 1225
Index 1 => 4986
Index 2 => 6789
Index 3 => 7890
Index 4 => 2345
Index 5 => 6783
Index 6 => 987
Index 7 => 1234
Index 8 => 8765
Index 9 => 3456

VI. Using iter and next:
1225 4986 6789 7890 2345 6783 987 1234 8765 3456 

VII. Using map function (Double the values):
[2450, 9972, 13578, 15780, 4690, 13566, 1974, 2468, 17530, 6912]

VIII. Using zip:
[(1225, 3456), (4986, 8765), (6789, 1234), (7890, 987), (2345, 6783), (6783, 2345), (987, 7890), (1234, 6789), (8765, 4986), (3456, 1225)]

IX. Using NumPy Module:
NumPy Array: [1225 4986 6789 7890 2345 6783  987 1234 8765 3456]
Sum of elements: 44460
Mean of elements: 4446.0
Squared elements: [ 1500625 2486

Question 3)	For a List A, B, C, D, E write a python program to compute all the combinations and permutations 

In [25]:
import itertools

# Step I: Define Lists A, B, C, D, E
A = [1, 2]
B = ['x', 'y']
C = ['@', '#']
D = [10, 20]
E = ['p', 'q']

# Step II: Compute all permutations (within each list)
print("Permutations within each list:")
for lst in [A, B, C, D, E]:
    perms = list(itertools.permutations(lst))
    print(f"Permutations of {lst}: {perms}")
print()

# Step III: Compute all combinations (choosing 2 elements from each list)
print("Combinations within each list (choosing 2 elements):")
for lst in [A, B, C, D, E]:
    if len(lst) >= 2:
        combs = list(itertools.combinations(lst, 2))
        print(f"Combinations of {lst}: {combs}")
print()

# Step IV: Compute all combinations of elements across lists (1 element from each list)
print("Combinations across lists (1 element from each list):")
all_combinations = list(itertools.product(A, B, C, D, E))
print(f"Combinations across A, B, C, D, E: {all_combinations}")
print()

# Step V: Compute permutations of elements across lists
print("Permutations across lists (1 element from each list):")
all_lists = A + B + C + D + E
all_permutations = list(itertools.permutations(all_lists, 5))  # Permutations of 5 elements
print(f"Permutations across A, B, C, D, E: {all_permutations[:10]} (showing first 10)")


Permutations within each list:
Permutations of [1, 2]: [(1, 2), (2, 1)]
Permutations of ['x', 'y']: [('x', 'y'), ('y', 'x')]
Permutations of ['@', '#']: [('@', '#'), ('#', '@')]
Permutations of [10, 20]: [(10, 20), (20, 10)]
Permutations of ['p', 'q']: [('p', 'q'), ('q', 'p')]

Combinations within each list (choosing 2 elements):
Combinations of [1, 2]: [(1, 2)]
Combinations of ['x', 'y']: [('x', 'y')]
Combinations of ['@', '#']: [('@', '#')]
Combinations of [10, 20]: [(10, 20)]
Combinations of ['p', 'q']: [('p', 'q')]

Combinations across lists (1 element from each list):
Combinations across A, B, C, D, E: [(1, 'x', '@', 10, 'p'), (1, 'x', '@', 10, 'q'), (1, 'x', '@', 20, 'p'), (1, 'x', '@', 20, 'q'), (1, 'x', '#', 10, 'p'), (1, 'x', '#', 10, 'q'), (1, 'x', '#', 20, 'p'), (1, 'x', '#', 20, 'q'), (1, 'y', '@', 10, 'p'), (1, 'y', '@', 10, 'q'), (1, 'y', '@', 20, 'p'), (1, 'y', '@', 20, 'q'), (1, 'y', '#', 10, 'p'), (1, 'y', '#', 10, 'q'), (1, 'y', '#', 20, 'p'), (1, 'y', '#', 20, 'q'), 

Question 4)	Using the same list use itertools compute permutations and combinations 


In [28]:
import itertools

# Define the lists A, B, C, D, E
A = [1, 2]
B = ['x', 'y']
C = ['@', '#']
D = [10, 20]
E = ['p', 'q']

# Combine all lists together for cross-list operations
all_lists = A + B + C + D + E

# Step I: Compute all permutations of the combined list
print("Permutations of the combined list (length 5):")
all_permutations = list(itertools.permutations(all_lists, 5))  # Permutations of 5 elements
print(f"Total Permutations: {len(all_permutations)}")
print(f"Sample Permutations (first 10): {all_permutations[:10]}")
print()

# Step II: Compute combinations within the combined list (choosing 5 elements)
print("Combinations of the combined list (choosing 5 elements):")
all_combinations = list(itertools.combinations(all_lists, 5))  # Combinations of 5 elements
print(f"Total Combinations: {len(all_combinations)}")
print(f"Sample Combinations (first 10): {all_combinations[:10]}")
print()

# Step III: Compute all permutations within each list
print("Permutations within each list:")
for lst in [A, B, C, D, E]:
    perms = list(itertools.permutations(lst))
    print(f"Permutations of {lst}: {perms}")
print()

# Step IV: Compute combinations within each list (choosing 2 elements where possible)
print("Combinations within each list (choosing 2 elements):")
for lst in [A, B, C, D, E]:
    if len(lst) >= 2:
        combs = list(itertools.combinations(lst, 2))
        print(f"Combinations of {lst}: {combs}")
print()


Permutations of the combined list (length 5):
Total Permutations: 30240
Sample Permutations (first 10): [(1, 2, 'x', 'y', '@'), (1, 2, 'x', 'y', '#'), (1, 2, 'x', 'y', 10), (1, 2, 'x', 'y', 20), (1, 2, 'x', 'y', 'p'), (1, 2, 'x', 'y', 'q'), (1, 2, 'x', '@', 'y'), (1, 2, 'x', '@', '#'), (1, 2, 'x', '@', 10), (1, 2, 'x', '@', 20)]

Combinations of the combined list (choosing 5 elements):
Total Combinations: 252
Sample Combinations (first 10): [(1, 2, 'x', 'y', '@'), (1, 2, 'x', 'y', '#'), (1, 2, 'x', 'y', 10), (1, 2, 'x', 'y', 20), (1, 2, 'x', 'y', 'p'), (1, 2, 'x', 'y', 'q'), (1, 2, 'x', '@', '#'), (1, 2, 'x', '@', 10), (1, 2, 'x', '@', 20), (1, 2, 'x', '@', 'p')]

Permutations within each list:
Permutations of [1, 2]: [(1, 2), (2, 1)]
Permutations of ['x', 'y']: [('x', 'y'), ('y', 'x')]
Permutations of ['@', '#']: [('@', '#'), ('#', '@')]
Permutations of [10, 20]: [(10, 20), (20, 10)]
Permutations of ['p', 'q']: [('p', 'q'), ('q', 'p')]

Combinations within each list (choosing 2 elemen